/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface WsConfigSchema100 {
  /**
   * IP address e.g. 192.168.1.1
   */
  wsIP: string;
  /**
   * port e.g. 1341
   */
  wsPort: string;
  /**
   * If the IP should be taken from the server where the client is provided.
   */
  detectServer: boolean;
  credentials: {
    /**
     * User login
     */
    login: string;
    /**
     * User password
     */
    password: string;
    [k: string]: any;
  };
  [k: string]: any;
}
