/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface CloudsAzureRequest100 {
  connectionString: string;
  [k: string]: any;
}
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface CloudsHexioRequest100 {
  broker: string;
  clientId: string;
  topicRequests: string;
  topicResponses: string;
  username: string;
  password: string;
  [k: string]: any;
}
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface CloudsIbmCloudRequest100 {
  organizationId: string;
  deviceType: string;
  token: string;
  eventId: string;
  [k: string]: any;
}
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface CloudsInteliGlueRequest100 {
  rootTopic: string;
  assignedPort: number;
  clientId: string;
  password: string;
  [k: string]: any;
}
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface GatewayInfoResponse100 {
  board: string;
  gwId: string;
  pixla: string;
  versions: {
    controller: string;
    daemon: string;
    webapp: string;
    [k: string]: any;
  };
  hostname: string;
  interfaces: {
    name: string;
    macAddress: string;
    ipAddresses: string[];
    [k: string]: any;
  }[];
  diskUsages: {
    fsName: string;
    fsType: string;
    size: string;
    used: string;
    available: string;
    usage: string;
    mount: string;
    [k: string]: any;
  }[];
  memoryUsage: {
    size: string;
    used: string;
    free: string;
    shared: string;
    buffers: string;
    cache: string;
    available: string;
    usage: string;
    [k: string]: any;
  };
  swapUsage: {
    size: string;
    used: string;
    free: string;
    usage: string;
    [k: string]: any;
  };
  coordinator: any;
  [k: string]: any;
}
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface SignInRequest100 {
  /**
   * user name
   */
  username: string;
  /**
   * password
   */
  password: string;
  [k: string]: any;
}
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface SignInResponse100 {
  /**
   * user name
   */
  token: string;
  [k: string]: any;
}
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface VersionResponse100 {
  version: string;
  commit: string;
  pipeline: string;
  [k: string]: any;
}
