/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface MqttConfigSchema100 {
  awsEndpoint: {
    /**
     * Your aws region.
     */
    region: string;
    /**
     * awsIotEndpoint
     */
    awsIotEndpoint: string;
    /**
     * Your accessKey ID.
     */
    accessKey: string;
    /**
     * Your secretKey ID.
     */
    secretKey: string;
    [k: string]: any;
  };
  mqttConfig: {
    /**
     * Port of MQTT Websockets transfer.
     */
    port: number;
    /**
     * Connect options for Paho.MQTT.Client connect function.
     */
    connectOptions: {
      useSSL: boolean;
      timeout: number;
      mqttVersion: number;
      [k: string]: any;
    };
    [k: string]: any;
  };
  [k: string]: any;
}
